import assert from 'node:assert/strict';
import { mkdir,writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { browserHarness } from './browserHarness.mjs';
const output=process.argv[2];if(!output)throw Error('Provide output directory');await mkdir(output,{recursive:true});
const b=await browserHarness(output),report={},panel=['场景1·纸纹序章'];
const stage=()=>b.evaluate('document.querySelector(".viewer-opening").dataset.stage');
try{
  await b.send('Runtime.discardConsoleEntries');await b.send('Emulation.setEmulatedMedia',{features:[]});
  await b.open({dream:true});
  report.labels=await b.evaluate(`Array.from(controller(['场景选择'],'当前场景').querySelector('select').options).map(o=>o.textContent)`);
  assert.equal(report.labels.length,12);assert.equal(report.labels[0],'场景1·纸纹序章');assert.equal(report.labels[1],'场景2·标本纵深');
  const original=await b.evaluate('__camera.position.toArray()');
  await b.set(['场景选择'],'当前场景','场景1·纸纹序章');
  await b.click(panel,'重播开场');await b.delay(220);assert.equal(await stage(),'line');await b.screenshot('01-line.png');
  await b.until(`document.querySelector('.viewer-opening').dataset.stage==='ready'`);
  await b.screenshot('02-circle-title.png');
  const idle=await b.evaluate('__renderCount');await b.delay(350);assert.equal(await b.evaluate('__renderCount'),idle);
  await b.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:720,y:500});await b.delay(450);await b.screenshot('03-enter-cursor.png');
  await b.send('Input.dispatchMouseEvent',{type:'mousePressed',x:720,y:500,button:'left',clickCount:1});
  await b.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:720,y:500,button:'left',clickCount:1});
  await b.delay(550);assert.equal(await stage(),'reveal');await b.screenshot('04-expansion.png');
  await b.until(`document.querySelector('.viewer-opening').dataset.stage==='paper'`);
  await b.screenshot('05-paper-only.png');
  assert.equal(await b.evaluate(`getComputedStyle(document.querySelector('.opening-enter img')).opacity`),'0');
  assert.equal(await b.evaluate(`document.querySelectorAll('.viewer-opening canvas,.viewer-opening iframe').length`),0);
  assert.equal(await b.evaluate(`getComputedStyle(document.querySelector('.viewer > canvas')).visibility`),'hidden');
  const points=[[100,100],[612,100],[100,612]];
  const samples=await b.screenshot(null,points);
  assert.deepEqual(samples[0],samples[1]);assert.deepEqual(samples[0],samples[2]);
  assert.ok(samples[0][0]>220,'paper texture tiles at native512px with no 3D content');
  // Existing scenes and camera state survive the insertion and return trip.
  await b.set(['场景选择'],'当前场景','场景2·标本纵深');await b.delay(180);
  assert.deepEqual(await b.evaluate('__camera.position.toArray()'),original);
  assert.equal(await b.evaluate('document.querySelector(".viewer-opening").hidden'),true);
  assert.equal(await b.evaluate(`getComputedStyle(document.querySelector('.viewer > canvas')).visibility`),'visible');
  await b.set(['场景选择'],'当前场景','场景12·字符物理实验');await b.delay(180);
  assert.ok(await b.evaluate(`__observed.findLast(o=>o.name==='场景12·字符物理实验').userData.character.ready`));
  await b.set(['场景选择'],'当前场景','场景1·纸纹序章');assert.equal(await stage(),'paper');
  await b.click(panel,'重播开场');await b.delay(200);
  await b.evaluate(`Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));`);
  const hiddenStage=await stage();await b.delay(1700);assert.equal(await stage(),hiddenStage);
  await b.evaluate(`delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));`);
  await b.until(`document.querySelector('.viewer-opening').dataset.stage==='ready'`);
  // Accessible native button activation and reduced-motion immediate entry.
  await b.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await b.evaluate(`document.querySelector('.opening-enter').focus()`);
  await b.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13,text:'\r'});
  await b.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13});await b.delay(100);assert.equal(await stage(),'paper');
  await b.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await b.click(panel,'重播开场');await b.delay(200);assert.equal(await stage(),'ready');await b.screenshot('06-mobile-title.png');
  await b.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await b.send('Emulation.setEmulatedMedia',{features:[]});
  const base=process.env.VIEWER_URL||'http://127.0.0.1:5173/';
  await b.send('Page.navigate',{url:new URL('/',base).href});
  await b.until(`document.querySelector('.viewer-scene-status')?.dataset.scene==='opening'`);
  await b.until(`document.querySelector('.viewer-opening')?.dataset.stage==='ready'`);
  report.defaultOpening=true;report.errors=b.errors;assert.equal(b.errors.length,0,JSON.stringify(b.errors));
  await writeFile(join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{b.close();}
