import { browserHarness } from './browserHarness.mjs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import assert from 'node:assert/strict';
const output = process.argv[2];
await mkdir(output, { recursive: true });
const b = await browserHarness(output), report = {};
const choose = label => b.set(['场景选择'], '当前场景', label);
const state = () => b.evaluate('sf.sketchbookScene.state');
try {
  await b.open({ dream: true });
  const camera = await b.evaluate('__camera.position.toArray()');
  await choose('场景10·狮城手记');
  await b.until(`document.querySelector('.viewer-sketchbook iframe')?.contentWindow?.sketchbookScene && document.querySelector('.viewer-sketchbook iframe').contentDocument.body.dataset.ready === '1'`);
  await b.evaluate(`window.sf=document.querySelector('.viewer-sketchbook iframe').contentWindow; window.sd=sf.document;`);
  await b.delay(5000);
  assert.equal(await b.evaluate('sd.documentElement.lang'), 'zh-CN');
  assert.equal(await b.evaluate('sd.querySelectorAll(".plate").length'), 9);
  assert.equal(await b.evaluate('document.querySelectorAll("canvas").length'), 1);
  await b.screenshot('01-desktop.png');
  await b.evaluate('sf.sketchbookScene.reset()'); await b.delay(300);
  await b.evaluate('sd.getElementById("sbRight").click()'); await b.delay(1500);
  assert.equal((await state()).page, 1);
  await b.evaluate('sd.getElementById("sbLeft").click()'); await b.delay(1500);
  assert.equal((await state()).page, 0);
  await b.evaluate('sd.getElementById("zIn").click()'); await b.delay(900);
  assert.ok((await state()).zoom > 1);
  await b.evaluate('sd.getElementById("loupeBtn").click()');
  assert.equal(await b.evaluate('sf.getComputedStyle(sd.getElementById("loupe")).visibility'), 'hidden');
  assert.equal(await b.evaluate('Number(sd.getElementById("zoomWrap").style.opacity)'), 0);
  await b.evaluate('sd.getElementById("loupeBtn").click(); sf.sketchbookScene.reset()');
  await b.delay(500);
  const bounds = await b.evaluate(`(()=>{const r=sd.querySelector('.loupe .ring').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);
  const mouse = (type, x, y, extra={}) => b.send('Input.dispatchMouseEvent', {type,x,y,...extra});
  const before = await b.evaluate('sd.getElementById("loupe").style.transform');
  await mouse('mousePressed',bounds.x,bounds.y,{button:'left',buttons:1,clickCount:1});
  await mouse('mouseMoved',bounds.x-140,bounds.y-90,{button:'left',buttons:1});
  await mouse('mouseReleased',bounds.x-140,bounds.y-90,{button:'left',buttons:0,clickCount:1});
  assert.notEqual(await b.evaluate('sd.getElementById("loupe").style.transform'), before);
  assert.equal((await state()).page, 0);
  await b.screenshot('02-loupe.png');
  for (let i=0;i<9;i++) {
    await b.evaluate(`sd.querySelectorAll('.plate')[${i}].click()`); await b.delay(1300);
    assert.equal((await state()).page,i);
    assert.ok(await b.evaluate('sd.querySelector("#sbBook .sb-full img").naturalWidth > 0'));
  }
  await b.evaluate('sd.getElementById("plates").scrollIntoView()'); await b.delay(500); await b.screenshot('03-index.png');
  const labels=['场景2·标本纵深','场景3·花粉星云','场景4·指尖花火','场景5·无限花开','场景6·纸飞机环游','场景7·蝶翼','场景8·斑驳光影','场景9·纵深花廊'];
  for (const label of labels) {
    await choose(label); assert.equal((await state()).active,false);
    await b.delay(100); await choose('场景10·狮城手记'); assert.equal((await state()).page,8);
  }
  assert.deepEqual(await b.evaluate('__camera.position.toArray()'),camera);
  await b.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await b.evaluate('sf.sketchbookScene.next()'); await b.delay(100);
  assert.equal((await state()).reduced,true); assert.equal((await state()).turning,false);
  await b.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:2,mobile:true});
  await b.evaluate('sf.sketchbookScene.reset()'); await b.delay(500);
  assert.equal(await b.evaluate('sd.documentElement.scrollWidth <= sf.innerWidth'),true);
  await b.screenshot('04-mobile.png');
  const r = await b.evaluate(`(()=>{const r=sd.getElementById('sbBook').getBoundingClientRect();return {x:r.x+r.width*.8,y:r.y+r.height*.45,w:r.width}})()`);
  await b.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x,y:r.y}]});
  await b.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x-r.w*.55,y:r.y}]});
  await b.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await b.delay(400); assert.equal((await state()).page,1);
  // Touch the smaller mobile loupe, without triggering a page turn.
  const lens = await b.evaluate(`(()=>{const r=sd.querySelector('.loupe .ring').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);
  const lensBefore = await b.evaluate('sd.getElementById("loupe").style.transform');
  await b.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:lens.x,y:lens.y}]});
  await b.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:lens.x-65,y:lens.y-40}]});
  await b.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.notEqual(await b.evaluate('sd.getElementById("loupe").style.transform'),lensBefore);
  assert.equal((await state()).page,1);
  await b.send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
  await b.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});
  await b.evaluate('sf.sketchbookScene.reset()'); await b.delay(400);
  const right = await b.evaluate(`(()=>{const r=sd.getElementById('sbRight').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);
  await mouse('mousePressed',right.x,right.y,{button:'left',buttons:1,clickCount:1});
  await mouse('mouseReleased',right.x,right.y,{button:'left',buttons:0,clickCount:1});
  await b.delay(1400); assert.equal((await state()).page,1);
  await b.send('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39});
  await b.send('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39});
  await b.delay(1400); assert.equal((await state()).page,2);
  await b.evaluate('sf.sketchbookScene.reset()'); await b.delay(300);
  const book = await b.evaluate(`(()=>{const r=sd.getElementById('sbBook').getBoundingClientRect();return {x:r.x+r.width*.85,y:r.y+r.height*.45,w:r.width}})()`);
  await mouse('mousePressed',book.x,book.y,{button:'left',buttons:1,clickCount:1});
  await mouse('mouseMoved',book.x-book.w*.27,book.y,{button:'left',buttons:1});
  await b.screenshot('05-page-curl.png');
  assert.equal(await b.evaluate('sd.querySelectorAll("#sbBook .strip").length'),18);
  await mouse('mouseMoved',book.x-12,book.y,{button:'left',buttons:1});
  await b.delay(80);
  await mouse('mouseReleased',book.x-12,book.y,{button:'left',buttons:0,clickCount:1});
  await b.delay(1400); assert.equal((await state()).page,0);
  await b.until('sf.eval("raf") === null');
  await b.evaluate('sf.sketchbookScene.next()');
  await choose('场景9·纵深花廊');
  assert.equal(await b.evaluate('sf.eval("raf")'),null);
  const frozen = await b.evaluate('sd.getElementById("sb3d").style.getPropertyValue("--tt")');
  await b.delay(300);
  assert.equal(await b.evaluate('sd.getElementById("sb3d").style.getPropertyValue("--tt")'),frozen);
  await choose('场景10·狮城手记'); await b.delay(1500);
  assert.equal((await state()).page,1);
  await b.evaluate(`(async()=>{window.extraHost=document.createElement('div'); extraHost.style.cssText='position:fixed;inset:0';document.body.append(extraHost);window.extra= (await import('/src/viewer/sketchbookScene.jsx')).createSketchbookScene(extraHost);extra.activate()})()`);
  await b.until('extraHost.querySelector("iframe")?.contentWindow.sketchbookScene');
  await b.evaluate('extra.dispose(); extra.dispose(); extraHost.remove()');
  await b.delay(100);
  assert.equal(await b.evaluate('document.querySelectorAll(".viewer-sketchbook iframe").length'),1);
  report.passed = ['all nine original paintings', 'native buttons, keyboard, zoom, loupe drag and hide', 'index navigation', 'all eight scene round trips and camera restoration', 'reduced motion', '390px mobile layout, touch page turn and loupe', '18-strip curl and drag cancellation', 'idle/hidden RAF stop and resume', 'idempotent document disposal'];
  assert.equal(b.errors.length,0,JSON.stringify(b.errors));
  report.errors=b.errors; await writeFile(join(output,'report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report));
} finally { await b.close(); }
